-- NutriCalc Supabase Schema & Initial Data


-- 1. Users Table
CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    name VARCHAR NOT NULL,
    age INTEGER NOT NULL,
    sex VARCHAR NOT NULL,
    height_cm FLOAT NOT NULL,
    weight_kg FLOAT NOT NULL,
    activity_level VARCHAR NOT NULL,
    goal VARCHAR DEFAULT 'maintain',
    region VARCHAR DEFAULT 'pan_india',
    state VARCHAR DEFAULT '',
    diet_type VARCHAR DEFAULT 'vegetarian',
    weekly_budget_inr FLOAT,
    allergies VARCHAR DEFAULT '',
    food_dislikes VARCHAR DEFAULT '',
    wake_time VARCHAR DEFAULT '07:00',
    sleep_time VARCHAR DEFAULT '23:00',
    exercise_time VARCHAR DEFAULT '',
    meals_per_day INTEGER DEFAULT 4,
    supabase_uid VARCHAR UNIQUE,
    email VARCHAR,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 2. Foods Table
CREATE TABLE IF NOT EXISTS foods (
    id SERIAL PRIMARY KEY,
    name VARCHAR NOT NULL,
    region VARCHAR NOT NULL,
    state VARCHAR DEFAULT '',
    diet_type VARCHAR NOT NULL,
    is_jain_friendly BOOLEAN DEFAULT FALSE,
    meal_slot VARCHAR NOT NULL,
    calories_per_serving FLOAT NOT NULL,
    protein_g FLOAT NOT NULL,
    carbs_g FLOAT NOT NULL,
    fat_g FLOAT NOT NULL,
    fiber_g FLOAT NOT NULL,
    iron_mg FLOAT NOT NULL,
    calcium_mg FLOAT DEFAULT 0,
    price_inr_per_serving FLOAT NOT NULL,
    allergens VARCHAR DEFAULT '',
    prep_method VARCHAR DEFAULT '',
    seasonality VARCHAR DEFAULT 'all_year'
);

-- 3. Meal Logs
CREATE TABLE IF NOT EXISTS meal_logs (
    id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    food_id INTEGER NOT NULL REFERENCES foods(id) ON DELETE CASCADE,
    meal_slot VARCHAR DEFAULT 'lunch',
    servings FLOAT DEFAULT 1.0,
    logged_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 4. Water Logs
CREATE TABLE IF NOT EXISTS water_logs (
    id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    amount_ml FLOAT NOT NULL,
    logged_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 5. Weight Logs
CREATE TABLE IF NOT EXISTS weight_logs (
    id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    weight_kg FLOAT NOT NULL,
    logged_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 6. Feedback
CREATE TABLE IF NOT EXISTS feedback (
    id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    food_id INTEGER NOT NULL REFERENCES foods(id) ON DELETE CASCADE,
    liked BOOLEAN NOT NULL,
    rating INTEGER,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Indexes
CREATE INDEX IF NOT EXISTS ix_foods_name ON foods(name);
CREATE INDEX IF NOT EXISTS ix_users_id ON users(id);


-- Seed 114 Indian Regional Foods

INSERT INTO foods (name, region, state, diet_type, is_jain_friendly, meal_slot, calories_per_serving, protein_g, carbs_g, fat_g, fiber_g, iron_mg, calcium_mg, price_inr_per_serving, allergens, prep_method, seasonality) VALUES ('Aloo Paratha (2 pcs)', 'north', '', 'vegetarian', FALSE, 'breakfast', 380, 10, 52, 14, 4, 2.5, 60, 40, 'gluten', 'fried', 'all_year');
INSERT INTO foods (name, region, state, diet_type, is_jain_friendly, meal_slot, calories_per_serving, protein_g, carbs_g, fat_g, fiber_g, iron_mg, calcium_mg, price_inr_per_serving, allergens, prep_method, seasonality) VALUES ('Poha with Peanuts', 'north', '', 'vegan', TRUE, 'breakfast', 270, 8, 42, 8, 3, 3.2, 30, 25, '', 'sauteed', 'all_year');
INSERT INTO foods (name, region, state, diet_type, is_jain_friendly, meal_slot, calories_per_serving, protein_g, carbs_g, fat_g, fiber_g, iron_mg, calcium_mg, price_inr_per_serving, allergens, prep_method, seasonality) VALUES ('Chole Bhature (1 plate)', 'north', '', 'vegetarian', FALSE, 'breakfast', 520, 14, 60, 24, 6, 3.8, 80, 60, 'gluten', 'fried', 'all_year');
INSERT INTO foods (name, region, state, diet_type, is_jain_friendly, meal_slot, calories_per_serving, protein_g, carbs_g, fat_g, fiber_g, iron_mg, calcium_mg, price_inr_per_serving, allergens, prep_method, seasonality) VALUES ('Stuffed Mooli Paratha', 'north', '', 'vegetarian', FALSE, 'breakfast', 340, 8, 48, 12, 5, 2.0, 50, 35, 'gluten', 'fried', 'winter');
INSERT INTO foods (name, region, state, diet_type, is_jain_friendly, meal_slot, calories_per_serving, protein_g, carbs_g, fat_g, fiber_g, iron_mg, calcium_mg, price_inr_per_serving, allergens, prep_method, seasonality) VALUES ('Besan Chilla (2 pcs)', 'north', '', 'vegan', TRUE, 'breakfast', 240, 12, 28, 8, 5, 2.8, 40, 20, '', 'pan_fried', 'all_year');
INSERT INTO foods (name, region, state, diet_type, is_jain_friendly, meal_slot, calories_per_serving, protein_g, carbs_g, fat_g, fiber_g, iron_mg, calcium_mg, price_inr_per_serving, allergens, prep_method, seasonality) VALUES ('Rajma Chawal (1 plate)', 'north', '', 'vegan', FALSE, 'lunch', 480, 16, 72, 10, 12, 4.5, 90, 45, '', 'boiled', 'all_year');
INSERT INTO foods (name, region, state, diet_type, is_jain_friendly, meal_slot, calories_per_serving, protein_g, carbs_g, fat_g, fiber_g, iron_mg, calcium_mg, price_inr_per_serving, allergens, prep_method, seasonality) VALUES ('Dal Makhani + 2 Roti', 'north', '', 'vegetarian', FALSE, 'lunch', 520, 18, 62, 20, 8, 4.2, 120, 55, 'dairy,gluten', 'slow_cook', 'all_year');
INSERT INTO foods (name, region, state, diet_type, is_jain_friendly, meal_slot, calories_per_serving, protein_g, carbs_g, fat_g, fiber_g, iron_mg, calcium_mg, price_inr_per_serving, allergens, prep_method, seasonality) VALUES ('Paneer Butter Masala + Rice', 'north', '', 'vegetarian', TRUE, 'lunch', 580, 22, 58, 28, 4, 2.5, 240, 70, 'dairy', 'sauteed', 'all_year');
INSERT INTO foods (name, region, state, diet_type, is_jain_friendly, meal_slot, calories_per_serving, protein_g, carbs_g, fat_g, fiber_g, iron_mg, calcium_mg, price_inr_per_serving, allergens, prep_method, seasonality) VALUES ('Chicken Curry + 2 Roti', 'north', '', 'non_vegetarian', FALSE, 'lunch', 550, 35, 48, 22, 4, 3.0, 40, 80, 'gluten', 'sauteed', 'all_year');
INSERT INTO foods (name, region, state, diet_type, is_jain_friendly, meal_slot, calories_per_serving, protein_g, carbs_g, fat_g, fiber_g, iron_mg, calcium_mg, price_inr_per_serving, allergens, prep_method, seasonality) VALUES ('Kadhi Chawal', 'north', '', 'vegetarian', FALSE, 'lunch', 420, 12, 60, 14, 3, 2.0, 140, 35, 'dairy', 'boiled', 'all_year');
INSERT INTO foods (name, region, state, diet_type, is_jain_friendly, meal_slot, calories_per_serving, protein_g, carbs_g, fat_g, fiber_g, iron_mg, calcium_mg, price_inr_per_serving, allergens, prep_method, seasonality) VALUES ('Roti + Aloo Gobi + Dal', 'north', '', 'vegan', FALSE, 'dinner', 440, 14, 62, 12, 8, 3.5, 70, 40, 'gluten', 'sauteed', 'all_year');
INSERT INTO foods (name, region, state, diet_type, is_jain_friendly, meal_slot, calories_per_serving, protein_g, carbs_g, fat_g, fiber_g, iron_mg, calcium_mg, price_inr_per_serving, allergens, prep_method, seasonality) VALUES ('Butter Chicken + Naan', 'north', '', 'non_vegetarian', FALSE, 'dinner', 620, 32, 50, 30, 3, 2.8, 60, 90, 'dairy,gluten', 'grilled', 'all_year');
INSERT INTO foods (name, region, state, diet_type, is_jain_friendly, meal_slot, calories_per_serving, protein_g, carbs_g, fat_g, fiber_g, iron_mg, calcium_mg, price_inr_per_serving, allergens, prep_method, seasonality) VALUES ('Palak Paneer + 2 Roti', 'north', '', 'vegetarian', TRUE, 'dinner', 460, 20, 44, 22, 6, 5.0, 280, 55, 'dairy,gluten', 'sauteed', 'all_year');
INSERT INTO foods (name, region, state, diet_type, is_jain_friendly, meal_slot, calories_per_serving, protein_g, carbs_g, fat_g, fiber_g, iron_mg, calcium_mg, price_inr_per_serving, allergens, prep_method, seasonality) VALUES ('Egg Curry + Rice', 'north', '', 'eggetarian', FALSE, 'dinner', 480, 20, 56, 18, 3, 3.0, 60, 50, 'eggs', 'boiled', 'all_year');
INSERT INTO foods (name, region, state, diet_type, is_jain_friendly, meal_slot, calories_per_serving, protein_g, carbs_g, fat_g, fiber_g, iron_mg, calcium_mg, price_inr_per_serving, allergens, prep_method, seasonality) VALUES ('Roasted Chana (50g)', 'north', '', 'vegan', TRUE, 'snack', 180, 10, 28, 3, 8, 3.0, 50, 15, '', 'roasted', 'all_year');
INSERT INTO foods (name, region, state, diet_type, is_jain_friendly, meal_slot, calories_per_serving, protein_g, carbs_g, fat_g, fiber_g, iron_mg, calcium_mg, price_inr_per_serving, allergens, prep_method, seasonality) VALUES ('Lassi (Sweet, 300ml)', 'north', '', 'vegetarian', TRUE, 'snack', 180, 6, 28, 5, 0, 0.2, 200, 20, 'dairy', 'blended', 'summer');
INSERT INTO foods (name, region, state, diet_type, is_jain_friendly, meal_slot, calories_per_serving, protein_g, carbs_g, fat_g, fiber_g, iron_mg, calcium_mg, price_inr_per_serving, allergens, prep_method, seasonality) VALUES ('Samosa (2 pcs)', 'north', '', 'vegetarian', FALSE, 'snack', 320, 6, 36, 16, 3, 1.5, 20, 25, 'gluten', 'fried', 'all_year');
INSERT INTO foods (name, region, state, diet_type, is_jain_friendly, meal_slot, calories_per_serving, protein_g, carbs_g, fat_g, fiber_g, iron_mg, calcium_mg, price_inr_per_serving, allergens, prep_method, seasonality) VALUES ('Idli (4 pcs) + Sambar', 'south', '', 'vegan', TRUE, 'breakfast', 280, 10, 48, 4, 4, 2.8, 40, 25, '', 'steamed', 'all_year');
INSERT INTO foods (name, region, state, diet_type, is_jain_friendly, meal_slot, calories_per_serving, protein_g, carbs_g, fat_g, fiber_g, iron_mg, calcium_mg, price_inr_per_serving, allergens, prep_method, seasonality) VALUES ('Masala Dosa + Chutney', 'south', '', 'vegan', TRUE, 'breakfast', 350, 8, 52, 12, 3, 2.5, 30, 30, '', 'pan_fried', 'all_year');
INSERT INTO foods (name, region, state, diet_type, is_jain_friendly, meal_slot, calories_per_serving, protein_g, carbs_g, fat_g, fiber_g, iron_mg, calcium_mg, price_inr_per_serving, allergens, prep_method, seasonality) VALUES ('Upma (Rava)', 'south', '', 'vegan', TRUE, 'breakfast', 260, 7, 40, 8, 3, 1.8, 20, 20, 'gluten', 'sauteed', 'all_year');
INSERT INTO foods (name, region, state, diet_type, is_jain_friendly, meal_slot, calories_per_serving, protein_g, carbs_g, fat_g, fiber_g, iron_mg, calcium_mg, price_inr_per_serving, allergens, prep_method, seasonality) VALUES ('Medu Vada (3 pcs) + Sambar', 'south', '', 'vegan', TRUE, 'breakfast', 380, 14, 42, 16, 6, 3.5, 50, 30, '', 'fried', 'all_year');
INSERT INTO foods (name, region, state, diet_type, is_jain_friendly, meal_slot, calories_per_serving, protein_g, carbs_g, fat_g, fiber_g, iron_mg, calcium_mg, price_inr_per_serving, allergens, prep_method, seasonality) VALUES ('Pesarattu (Moong Dosa, 2)', 'south', '', 'vegan', TRUE, 'breakfast', 280, 14, 36, 6, 6, 3.2, 40, 25, '', 'pan_fried', 'all_year');
INSERT INTO foods (name, region, state, diet_type, is_jain_friendly, meal_slot, calories_per_serving, protein_g, carbs_g, fat_g, fiber_g, iron_mg, calcium_mg, price_inr_per_serving, allergens, prep_method, seasonality) VALUES ('Pongal (Ven Pongal)', 'south', '', 'vegetarian', TRUE, 'breakfast', 320, 8, 48, 10, 2, 1.5, 30, 25, 'dairy', 'boiled', 'all_year');
INSERT INTO foods (name, region, state, diet_type, is_jain_friendly, meal_slot, calories_per_serving, protein_g, carbs_g, fat_g, fiber_g, iron_mg, calcium_mg, price_inr_per_serving, allergens, prep_method, seasonality) VALUES ('Sambar Rice + Papad', 'south', '', 'vegan', TRUE, 'lunch', 420, 12, 68, 8, 8, 3.8, 50, 30, '', 'boiled', 'all_year');
INSERT INTO foods (name, region, state, diet_type, is_jain_friendly, meal_slot, calories_per_serving, protein_g, carbs_g, fat_g, fiber_g, iron_mg, calcium_mg, price_inr_per_serving, allergens, prep_method, seasonality) VALUES ('Curd Rice', 'south', '', 'vegetarian', TRUE, 'lunch', 320, 10, 52, 8, 2, 1.0, 180, 25, 'dairy', 'raw', 'summer');
INSERT INTO foods (name, region, state, diet_type, is_jain_friendly, meal_slot, calories_per_serving, protein_g, carbs_g, fat_g, fiber_g, iron_mg, calcium_mg, price_inr_per_serving, allergens, prep_method, seasonality) VALUES ('Fish Curry + Rice (Kerala)', 'south', '', 'non_vegetarian', FALSE, 'lunch', 520, 30, 54, 18, 3, 2.5, 60, 75, 'fish', 'sauteed', 'all_year');
INSERT INTO foods (name, region, state, diet_type, is_jain_friendly, meal_slot, calories_per_serving, protein_g, carbs_g, fat_g, fiber_g, iron_mg, calcium_mg, price_inr_per_serving, allergens, prep_method, seasonality) VALUES ('Bisi Bele Bath', 'south', '', 'vegetarian', TRUE, 'lunch', 450, 14, 64, 12, 8, 3.5, 60, 35, 'nuts', 'boiled', 'all_year');
INSERT INTO foods (name, region, state, diet_type, is_jain_friendly, meal_slot, calories_per_serving, protein_g, carbs_g, fat_g, fiber_g, iron_mg, calcium_mg, price_inr_per_serving, allergens, prep_method, seasonality) VALUES ('Rasam Rice + Vegetable', 'south', '', 'vegan', TRUE, 'lunch', 380, 10, 62, 6, 5, 2.8, 40, 25, '', 'boiled', 'all_year');
INSERT INTO foods (name, region, state, diet_type, is_jain_friendly, meal_slot, calories_per_serving, protein_g, carbs_g, fat_g, fiber_g, iron_mg, calcium_mg, price_inr_per_serving, allergens, prep_method, seasonality) VALUES ('Appam + Stew (Veg)', 'south', '', 'vegetarian', TRUE, 'dinner', 380, 8, 52, 14, 4, 1.5, 30, 30, 'dairy', 'steamed', 'all_year');
INSERT INTO foods (name, region, state, diet_type, is_jain_friendly, meal_slot, calories_per_serving, protein_g, carbs_g, fat_g, fiber_g, iron_mg, calcium_mg, price_inr_per_serving, allergens, prep_method, seasonality) VALUES ('Meen Pollichathu (Fish)', 'south', '', 'non_vegetarian', FALSE, 'dinner', 420, 28, 30, 20, 3, 2.0, 50, 85, 'fish', 'baked', 'all_year');
INSERT INTO foods (name, region, state, diet_type, is_jain_friendly, meal_slot, calories_per_serving, protein_g, carbs_g, fat_g, fiber_g, iron_mg, calcium_mg, price_inr_per_serving, allergens, prep_method, seasonality) VALUES ('Lemon Rice + Raita', 'south', '', 'vegetarian', TRUE, 'dinner', 380, 8, 58, 10, 3, 1.5, 80, 25, 'dairy,nuts', 'sauteed', 'all_year');
INSERT INTO foods (name, region, state, diet_type, is_jain_friendly, meal_slot, calories_per_serving, protein_g, carbs_g, fat_g, fiber_g, iron_mg, calcium_mg, price_inr_per_serving, allergens, prep_method, seasonality) VALUES ('Ragi Mudde + Sambar', 'south', '', 'vegan', TRUE, 'dinner', 360, 10, 60, 4, 8, 4.5, 340, 20, '', 'boiled', 'all_year');
INSERT INTO foods (name, region, state, diet_type, is_jain_friendly, meal_slot, calories_per_serving, protein_g, carbs_g, fat_g, fiber_g, iron_mg, calcium_mg, price_inr_per_serving, allergens, prep_method, seasonality) VALUES ('Banana Chips (50g)', 'south', '', 'vegan', TRUE, 'snack', 260, 2, 30, 16, 2, 0.5, 10, 15, '', 'fried', 'all_year');
INSERT INTO foods (name, region, state, diet_type, is_jain_friendly, meal_slot, calories_per_serving, protein_g, carbs_g, fat_g, fiber_g, iron_mg, calcium_mg, price_inr_per_serving, allergens, prep_method, seasonality) VALUES ('Filter Coffee + Biscuit', 'south', '', 'vegetarian', TRUE, 'snack', 120, 3, 18, 4, 0, 0.3, 80, 15, 'dairy,gluten', 'brewed', 'all_year');
INSERT INTO foods (name, region, state, diet_type, is_jain_friendly, meal_slot, calories_per_serving, protein_g, carbs_g, fat_g, fiber_g, iron_mg, calcium_mg, price_inr_per_serving, allergens, prep_method, seasonality) VALUES ('Murukku (50g)', 'south', '', 'vegan', TRUE, 'snack', 240, 4, 32, 12, 2, 1.0, 15, 10, '', 'fried', 'all_year');
INSERT INTO foods (name, region, state, diet_type, is_jain_friendly, meal_slot, calories_per_serving, protein_g, carbs_g, fat_g, fiber_g, iron_mg, calcium_mg, price_inr_per_serving, allergens, prep_method, seasonality) VALUES ('Misal Pav', 'west', '', 'vegan', FALSE, 'breakfast', 400, 14, 52, 14, 8, 4.0, 60, 35, 'gluten', 'sauteed', 'all_year');
INSERT INTO foods (name, region, state, diet_type, is_jain_friendly, meal_slot, calories_per_serving, protein_g, carbs_g, fat_g, fiber_g, iron_mg, calcium_mg, price_inr_per_serving, allergens, prep_method, seasonality) VALUES ('Thepla (3 pcs) + Curd', 'west', '', 'vegetarian', TRUE, 'breakfast', 340, 10, 44, 14, 4, 2.5, 80, 25, 'dairy,gluten', 'pan_fried', 'all_year');
INSERT INTO foods (name, region, state, diet_type, is_jain_friendly, meal_slot, calories_per_serving, protein_g, carbs_g, fat_g, fiber_g, iron_mg, calcium_mg, price_inr_per_serving, allergens, prep_method, seasonality) VALUES ('Sabudana Khichdi', 'west', '', 'vegetarian', TRUE, 'breakfast', 320, 6, 52, 10, 2, 1.0, 30, 30, 'nuts', 'sauteed', 'all_year');
INSERT INTO foods (name, region, state, diet_type, is_jain_friendly, meal_slot, calories_per_serving, protein_g, carbs_g, fat_g, fiber_g, iron_mg, calcium_mg, price_inr_per_serving, allergens, prep_method, seasonality) VALUES ('Dhokla (4 pcs)', 'west', '', 'vegan', TRUE, 'breakfast', 220, 8, 36, 4, 3, 2.0, 20, 15, '', 'steamed', 'all_year');
INSERT INTO foods (name, region, state, diet_type, is_jain_friendly, meal_slot, calories_per_serving, protein_g, carbs_g, fat_g, fiber_g, iron_mg, calcium_mg, price_inr_per_serving, allergens, prep_method, seasonality) VALUES ('Khandvi (6 pcs)', 'west', '', 'vegetarian', TRUE, 'breakfast', 200, 8, 28, 6, 2, 1.5, 30, 20, '', 'steamed', 'all_year');
INSERT INTO foods (name, region, state, diet_type, is_jain_friendly, meal_slot, calories_per_serving, protein_g, carbs_g, fat_g, fiber_g, iron_mg, calcium_mg, price_inr_per_serving, allergens, prep_method, seasonality) VALUES ('Pav Bhaji (1 plate)', 'west', '', 'vegetarian', FALSE, 'lunch', 520, 12, 60, 24, 6, 3.0, 60, 45, 'dairy,gluten', 'sauteed', 'all_year');
INSERT INTO foods (name, region, state, diet_type, is_jain_friendly, meal_slot, calories_per_serving, protein_g, carbs_g, fat_g, fiber_g, iron_mg, calcium_mg, price_inr_per_serving, allergens, prep_method, seasonality) VALUES ('Undhiyu + Rotla', 'west', '', 'vegetarian', TRUE, 'lunch', 480, 14, 56, 20, 10, 4.5, 80, 40, 'gluten', 'slow_cook', 'winter');
INSERT INTO foods (name, region, state, diet_type, is_jain_friendly, meal_slot, calories_per_serving, protein_g, carbs_g, fat_g, fiber_g, iron_mg, calcium_mg, price_inr_per_serving, allergens, prep_method, seasonality) VALUES ('Puran Poli + Amti', 'west', '', 'vegetarian', TRUE, 'lunch', 440, 10, 68, 12, 6, 3.0, 50, 30, 'gluten', 'pan_fried', 'all_year');
INSERT INTO foods (name, region, state, diet_type, is_jain_friendly, meal_slot, calories_per_serving, protein_g, carbs_g, fat_g, fiber_g, iron_mg, calcium_mg, price_inr_per_serving, allergens, prep_method, seasonality) VALUES ('Fish Thali (Goan)', 'west', '', 'non_vegetarian', FALSE, 'lunch', 580, 32, 54, 22, 5, 3.5, 80, 90, 'fish', 'sauteed', 'all_year');
INSERT INTO foods (name, region, state, diet_type, is_jain_friendly, meal_slot, calories_per_serving, protein_g, carbs_g, fat_g, fiber_g, iron_mg, calcium_mg, price_inr_per_serving, allergens, prep_method, seasonality) VALUES ('Gujarati Dal + Rice + Roti', 'west', '', 'vegetarian', TRUE, 'lunch', 460, 14, 66, 12, 6, 3.2, 60, 35, 'dairy,gluten', 'boiled', 'all_year');
INSERT INTO foods (name, region, state, diet_type, is_jain_friendly, meal_slot, calories_per_serving, protein_g, carbs_g, fat_g, fiber_g, iron_mg, calcium_mg, price_inr_per_serving, allergens, prep_method, seasonality) VALUES ('Bhakri + Zunka', 'west', '', 'vegan', TRUE, 'dinner', 380, 12, 54, 10, 8, 3.5, 40, 20, '', 'roasted', 'all_year');
INSERT INTO foods (name, region, state, diet_type, is_jain_friendly, meal_slot, calories_per_serving, protein_g, carbs_g, fat_g, fiber_g, iron_mg, calcium_mg, price_inr_per_serving, allergens, prep_method, seasonality) VALUES ('Varan Bhaat + Toop', 'west', '', 'vegetarian', TRUE, 'dinner', 420, 12, 60, 14, 5, 2.5, 40, 30, 'dairy', 'boiled', 'all_year');
INSERT INTO foods (name, region, state, diet_type, is_jain_friendly, meal_slot, calories_per_serving, protein_g, carbs_g, fat_g, fiber_g, iron_mg, calcium_mg, price_inr_per_serving, allergens, prep_method, seasonality) VALUES ('Chicken Xacuti (Goan)', 'west', '', 'non_vegetarian', FALSE, 'dinner', 480, 28, 32, 26, 4, 3.0, 50, 85, 'nuts', 'sauteed', 'all_year');
INSERT INTO foods (name, region, state, diet_type, is_jain_friendly, meal_slot, calories_per_serving, protein_g, carbs_g, fat_g, fiber_g, iron_mg, calcium_mg, price_inr_per_serving, allergens, prep_method, seasonality) VALUES ('Fafda + Jalebi', 'west', '', 'vegetarian', TRUE, 'snack', 380, 6, 52, 16, 2, 1.0, 20, 30, 'gluten,dairy', 'fried', 'all_year');
INSERT INTO foods (name, region, state, diet_type, is_jain_friendly, meal_slot, calories_per_serving, protein_g, carbs_g, fat_g, fiber_g, iron_mg, calcium_mg, price_inr_per_serving, allergens, prep_method, seasonality) VALUES ('Dabeli', 'west', '', 'vegan', FALSE, 'snack', 280, 6, 40, 10, 3, 2.0, 30, 25, 'gluten,nuts', 'grilled', 'all_year');
INSERT INTO foods (name, region, state, diet_type, is_jain_friendly, meal_slot, calories_per_serving, protein_g, carbs_g, fat_g, fiber_g, iron_mg, calcium_mg, price_inr_per_serving, allergens, prep_method, seasonality) VALUES ('Makhana Roasted (50g)', 'west', '', 'vegan', TRUE, 'snack', 180, 5, 28, 4, 3, 1.8, 40, 15, '', 'roasted', 'all_year');
INSERT INTO foods (name, region, state, diet_type, is_jain_friendly, meal_slot, calories_per_serving, protein_g, carbs_g, fat_g, fiber_g, iron_mg, calcium_mg, price_inr_per_serving, allergens, prep_method, seasonality) VALUES ('Luchi + Aloor Dom', 'east', '', 'vegetarian', FALSE, 'breakfast', 420, 8, 52, 20, 3, 2.0, 30, 35, 'gluten', 'fried', 'all_year');
INSERT INTO foods (name, region, state, diet_type, is_jain_friendly, meal_slot, calories_per_serving, protein_g, carbs_g, fat_g, fiber_g, iron_mg, calcium_mg, price_inr_per_serving, allergens, prep_method, seasonality) VALUES ('Chirer Polao (Flattened Rice)', 'east', '', 'vegetarian', TRUE, 'breakfast', 300, 6, 48, 8, 3, 2.5, 30, 20, 'nuts', 'sauteed', 'all_year');
INSERT INTO foods (name, region, state, diet_type, is_jain_friendly, meal_slot, calories_per_serving, protein_g, carbs_g, fat_g, fiber_g, iron_mg, calcium_mg, price_inr_per_serving, allergens, prep_method, seasonality) VALUES ('Sattu Paratha (2 pcs)', 'east', '', 'vegan', TRUE, 'breakfast', 360, 14, 48, 10, 6, 3.8, 50, 25, 'gluten', 'pan_fried', 'all_year');
INSERT INTO foods (name, region, state, diet_type, is_jain_friendly, meal_slot, calories_per_serving, protein_g, carbs_g, fat_g, fiber_g, iron_mg, calcium_mg, price_inr_per_serving, allergens, prep_method, seasonality) VALUES ('Maachher Jhol + Rice', 'east', '', 'non_vegetarian', FALSE, 'lunch', 480, 26, 58, 14, 3, 2.5, 60, 60, 'fish', 'sauteed', 'all_year');
INSERT INTO foods (name, region, state, diet_type, is_jain_friendly, meal_slot, calories_per_serving, protein_g, carbs_g, fat_g, fiber_g, iron_mg, calcium_mg, price_inr_per_serving, allergens, prep_method, seasonality) VALUES ('Dalma + Rice (Odia)', 'east', '', 'vegan', TRUE, 'lunch', 420, 14, 64, 8, 10, 4.0, 60, 30, '', 'boiled', 'all_year');
INSERT INTO foods (name, region, state, diet_type, is_jain_friendly, meal_slot, calories_per_serving, protein_g, carbs_g, fat_g, fiber_g, iron_mg, calcium_mg, price_inr_per_serving, allergens, prep_method, seasonality) VALUES ('Shukto + Rice + Dal', 'east', '', 'vegetarian', TRUE, 'lunch', 440, 12, 62, 12, 8, 3.5, 80, 35, 'dairy', 'sauteed', 'all_year');
INSERT INTO foods (name, region, state, diet_type, is_jain_friendly, meal_slot, calories_per_serving, protein_g, carbs_g, fat_g, fiber_g, iron_mg, calcium_mg, price_inr_per_serving, allergens, prep_method, seasonality) VALUES ('Litti Chokha (3 pcs)', 'east', '', 'vegan', TRUE, 'lunch', 480, 16, 60, 16, 8, 4.2, 50, 30, 'gluten', 'baked', 'all_year');
INSERT INTO foods (name, region, state, diet_type, is_jain_friendly, meal_slot, calories_per_serving, protein_g, carbs_g, fat_g, fiber_g, iron_mg, calcium_mg, price_inr_per_serving, allergens, prep_method, seasonality) VALUES ('Mishti Doi + Light Rice', 'east', '', 'vegetarian', TRUE, 'dinner', 380, 8, 58, 10, 2, 1.0, 150, 30, 'dairy', 'raw', 'all_year');
INSERT INTO foods (name, region, state, diet_type, is_jain_friendly, meal_slot, calories_per_serving, protein_g, carbs_g, fat_g, fiber_g, iron_mg, calcium_mg, price_inr_per_serving, allergens, prep_method, seasonality) VALUES ('Egg Bhurji + 2 Paratha', 'east', '', 'eggetarian', FALSE, 'dinner', 480, 20, 44, 24, 3, 3.0, 60, 45, 'eggs,gluten', 'sauteed', 'all_year');
INSERT INTO foods (name, region, state, diet_type, is_jain_friendly, meal_slot, calories_per_serving, protein_g, carbs_g, fat_g, fiber_g, iron_mg, calcium_mg, price_inr_per_serving, allergens, prep_method, seasonality) VALUES ('Begun Bhaja + Dal + Rice', 'east', '', 'vegan', TRUE, 'dinner', 440, 12, 62, 14, 6, 3.0, 40, 30, '', 'fried', 'all_year');
INSERT INTO foods (name, region, state, diet_type, is_jain_friendly, meal_slot, calories_per_serving, protein_g, carbs_g, fat_g, fiber_g, iron_mg, calcium_mg, price_inr_per_serving, allergens, prep_method, seasonality) VALUES ('Jhalmuri', 'east', '', 'vegan', TRUE, 'snack', 200, 5, 32, 6, 3, 2.0, 20, 15, '', 'raw', 'all_year');
INSERT INTO foods (name, region, state, diet_type, is_jain_friendly, meal_slot, calories_per_serving, protein_g, carbs_g, fat_g, fiber_g, iron_mg, calcium_mg, price_inr_per_serving, allergens, prep_method, seasonality) VALUES ('Singara (Samosa, 2 pcs)', 'east', '', 'vegetarian', FALSE, 'snack', 300, 6, 34, 14, 3, 1.5, 20, 20, 'gluten', 'fried', 'all_year');
INSERT INTO foods (name, region, state, diet_type, is_jain_friendly, meal_slot, calories_per_serving, protein_g, carbs_g, fat_g, fiber_g, iron_mg, calcium_mg, price_inr_per_serving, allergens, prep_method, seasonality) VALUES ('Pitha (Rice Cake, 3 pcs)', 'northeast', '', 'vegan', TRUE, 'breakfast', 300, 6, 52, 6, 3, 1.5, 20, 20, '', 'steamed', 'all_year');
INSERT INTO foods (name, region, state, diet_type, is_jain_friendly, meal_slot, calories_per_serving, protein_g, carbs_g, fat_g, fiber_g, iron_mg, calcium_mg, price_inr_per_serving, allergens, prep_method, seasonality) VALUES ('Jolpan (Assamese Flattened Rice)', 'northeast', '', 'vegan', TRUE, 'breakfast', 280, 6, 46, 8, 3, 2.0, 30, 15, '', 'raw', 'all_year');
INSERT INTO foods (name, region, state, diet_type, is_jain_friendly, meal_slot, calories_per_serving, protein_g, carbs_g, fat_g, fiber_g, iron_mg, calcium_mg, price_inr_per_serving, allergens, prep_method, seasonality) VALUES ('Bamboo Shoot Curry + Rice', 'northeast', '', 'vegan', TRUE, 'lunch', 380, 10, 56, 10, 6, 2.5, 30, 30, '', 'boiled', 'all_year');
INSERT INTO foods (name, region, state, diet_type, is_jain_friendly, meal_slot, calories_per_serving, protein_g, carbs_g, fat_g, fiber_g, iron_mg, calcium_mg, price_inr_per_serving, allergens, prep_method, seasonality) VALUES ('Smoked Pork + Rice (Naga)', 'northeast', '', 'non_vegetarian', FALSE, 'lunch', 520, 30, 50, 22, 3, 3.0, 20, 70, '', 'smoked', 'all_year');
INSERT INTO foods (name, region, state, diet_type, is_jain_friendly, meal_slot, calories_per_serving, protein_g, carbs_g, fat_g, fiber_g, iron_mg, calcium_mg, price_inr_per_serving, allergens, prep_method, seasonality) VALUES ('Dal + Rice + Ou Tenga', 'northeast', '', 'vegan', TRUE, 'lunch', 400, 14, 60, 8, 6, 3.5, 40, 25, '', 'boiled', 'all_year');
INSERT INTO foods (name, region, state, diet_type, is_jain_friendly, meal_slot, calories_per_serving, protein_g, carbs_g, fat_g, fiber_g, iron_mg, calcium_mg, price_inr_per_serving, allergens, prep_method, seasonality) VALUES ('Khaar + Rice (Assamese)', 'northeast', '', 'vegetarian', TRUE, 'dinner', 360, 8, 56, 8, 4, 2.0, 30, 20, '', 'boiled', 'all_year');
INSERT INTO foods (name, region, state, diet_type, is_jain_friendly, meal_slot, calories_per_serving, protein_g, carbs_g, fat_g, fiber_g, iron_mg, calcium_mg, price_inr_per_serving, allergens, prep_method, seasonality) VALUES ('Jadoh (Meghalaya Rice)', 'northeast', '', 'non_vegetarian', FALSE, 'dinner', 480, 22, 52, 16, 3, 2.5, 30, 50, '', 'boiled', 'all_year');
INSERT INTO foods (name, region, state, diet_type, is_jain_friendly, meal_slot, calories_per_serving, protein_g, carbs_g, fat_g, fiber_g, iron_mg, calcium_mg, price_inr_per_serving, allergens, prep_method, seasonality) VALUES ('Vegetable Momos (8 pcs)', 'northeast', '', 'vegetarian', TRUE, 'snack', 320, 10, 50, 8, 4, 1.6, 30, 50, 'gluten', 'steamed', 'all_year');
INSERT INTO foods (name, region, state, diet_type, is_jain_friendly, meal_slot, calories_per_serving, protein_g, carbs_g, fat_g, fiber_g, iron_mg, calcium_mg, price_inr_per_serving, allergens, prep_method, seasonality) VALUES ('Chicken Momos (8 pcs)', 'northeast', '', 'non_vegetarian', FALSE, 'snack', 380, 18, 46, 12, 3, 2.0, 30, 60, 'gluten', 'steamed', 'all_year');
INSERT INTO foods (name, region, state, diet_type, is_jain_friendly, meal_slot, calories_per_serving, protein_g, carbs_g, fat_g, fiber_g, iron_mg, calcium_mg, price_inr_per_serving, allergens, prep_method, seasonality) VALUES ('Poha Jalebi', 'central', '', 'vegetarian', TRUE, 'breakfast', 380, 8, 56, 14, 3, 2.0, 30, 30, 'gluten', 'fried', 'all_year');
INSERT INTO foods (name, region, state, diet_type, is_jain_friendly, meal_slot, calories_per_serving, protein_g, carbs_g, fat_g, fiber_g, iron_mg, calcium_mg, price_inr_per_serving, allergens, prep_method, seasonality) VALUES ('Bafla (Baked Wheat Balls)', 'central', '', 'vegetarian', TRUE, 'breakfast', 400, 10, 58, 14, 4, 2.5, 40, 25, 'gluten,dairy', 'baked', 'all_year');
INSERT INTO foods (name, region, state, diet_type, is_jain_friendly, meal_slot, calories_per_serving, protein_g, carbs_g, fat_g, fiber_g, iron_mg, calcium_mg, price_inr_per_serving, allergens, prep_method, seasonality) VALUES ('Dal Bafla + Churma', 'central', '', 'vegetarian', TRUE, 'lunch', 540, 16, 72, 18, 6, 3.5, 50, 40, 'gluten,dairy', 'baked', 'all_year');
INSERT INTO foods (name, region, state, diet_type, is_jain_friendly, meal_slot, calories_per_serving, protein_g, carbs_g, fat_g, fiber_g, iron_mg, calcium_mg, price_inr_per_serving, allergens, prep_method, seasonality) VALUES ('Chhattisgarhi Chila + Chutney', 'central', '', 'vegan', TRUE, 'lunch', 320, 10, 42, 10, 5, 3.0, 40, 20, '', 'pan_fried', 'all_year');
INSERT INTO foods (name, region, state, diet_type, is_jain_friendly, meal_slot, calories_per_serving, protein_g, carbs_g, fat_g, fiber_g, iron_mg, calcium_mg, price_inr_per_serving, allergens, prep_method, seasonality) VALUES ('Bhutte ka Kees + Roti', 'central', '', 'vegetarian', TRUE, 'lunch', 380, 10, 52, 14, 5, 2.5, 40, 30, 'dairy,gluten', 'sauteed', 'monsoon');
INSERT INTO foods (name, region, state, diet_type, is_jain_friendly, meal_slot, calories_per_serving, protein_g, carbs_g, fat_g, fiber_g, iron_mg, calcium_mg, price_inr_per_serving, allergens, prep_method, seasonality) VALUES ('Roti + Sev Tamatar + Dal', 'central', '', 'vegan', TRUE, 'dinner', 420, 14, 58, 12, 6, 3.5, 40, 30, 'gluten', 'sauteed', 'all_year');
INSERT INTO foods (name, region, state, diet_type, is_jain_friendly, meal_slot, calories_per_serving, protein_g, carbs_g, fat_g, fiber_g, iron_mg, calcium_mg, price_inr_per_serving, allergens, prep_method, seasonality) VALUES ('Malpua + Light Dal Rice', 'central', '', 'vegetarian', TRUE, 'dinner', 460, 10, 66, 16, 4, 2.0, 50, 35, 'dairy,gluten', 'fried', 'all_year');
INSERT INTO foods (name, region, state, diet_type, is_jain_friendly, meal_slot, calories_per_serving, protein_g, carbs_g, fat_g, fiber_g, iron_mg, calcium_mg, price_inr_per_serving, allergens, prep_method, seasonality) VALUES ('Bhutte ka Kees (snack)', 'central', '', 'vegetarian', TRUE, 'snack', 200, 5, 28, 8, 3, 1.5, 20, 15, 'dairy', 'sauteed', 'monsoon');
INSERT INTO foods (name, region, state, diet_type, is_jain_friendly, meal_slot, calories_per_serving, protein_g, carbs_g, fat_g, fiber_g, iron_mg, calcium_mg, price_inr_per_serving, allergens, prep_method, seasonality) VALUES ('Chana Jor Garam', 'central', '', 'vegan', TRUE, 'snack', 180, 8, 24, 5, 5, 2.5, 30, 10, '', 'roasted', 'all_year');
INSERT INTO foods (name, region, state, diet_type, is_jain_friendly, meal_slot, calories_per_serving, protein_g, carbs_g, fat_g, fiber_g, iron_mg, calcium_mg, price_inr_per_serving, allergens, prep_method, seasonality) VALUES ('Vegetable Oats Porridge', 'pan_india', '', 'vegan', TRUE, 'breakfast', 220, 8, 36, 6, 5, 2.5, 30, 15, 'gluten', 'boiled', 'all_year');
INSERT INTO foods (name, region, state, diet_type, is_jain_friendly, meal_slot, calories_per_serving, protein_g, carbs_g, fat_g, fiber_g, iron_mg, calcium_mg, price_inr_per_serving, allergens, prep_method, seasonality) VALUES ('Moong Dal Chilla (2 pcs)', 'pan_india', '', 'vegan', TRUE, 'breakfast', 260, 14, 32, 6, 6, 2.8, 30, 25, '', 'pan_fried', 'all_year');
INSERT INTO foods (name, region, state, diet_type, is_jain_friendly, meal_slot, calories_per_serving, protein_g, carbs_g, fat_g, fiber_g, iron_mg, calcium_mg, price_inr_per_serving, allergens, prep_method, seasonality) VALUES ('Boiled Eggs (2) + Toast', 'pan_india', '', 'eggetarian', FALSE, 'breakfast', 280, 16, 24, 12, 2, 2.0, 50, 30, 'eggs,gluten', 'boiled', 'all_year');
INSERT INTO foods (name, region, state, diet_type, is_jain_friendly, meal_slot, calories_per_serving, protein_g, carbs_g, fat_g, fiber_g, iron_mg, calcium_mg, price_inr_per_serving, allergens, prep_method, seasonality) VALUES ('Sprouts Salad', 'pan_india', '', 'vegan', TRUE, 'breakfast', 180, 12, 24, 3, 8, 3.5, 40, 10, '', 'raw', 'all_year');
INSERT INTO foods (name, region, state, diet_type, is_jain_friendly, meal_slot, calories_per_serving, protein_g, carbs_g, fat_g, fiber_g, iron_mg, calcium_mg, price_inr_per_serving, allergens, prep_method, seasonality) VALUES ('Paneer Paratha (2)', 'pan_india', '', 'vegetarian', TRUE, 'breakfast', 420, 16, 44, 20, 3, 2.0, 200, 45, 'dairy,gluten', 'pan_fried', 'all_year');
INSERT INTO foods (name, region, state, diet_type, is_jain_friendly, meal_slot, calories_per_serving, protein_g, carbs_g, fat_g, fiber_g, iron_mg, calcium_mg, price_inr_per_serving, allergens, prep_method, seasonality) VALUES ('Banana Smoothie (300ml)', 'pan_india', '', 'vegetarian', TRUE, 'breakfast', 240, 8, 40, 6, 3, 0.5, 160, 20, 'dairy', 'blended', 'all_year');
INSERT INTO foods (name, region, state, diet_type, is_jain_friendly, meal_slot, calories_per_serving, protein_g, carbs_g, fat_g, fiber_g, iron_mg, calcium_mg, price_inr_per_serving, allergens, prep_method, seasonality) VALUES ('Grilled Paneer Salad', 'pan_india', '', 'vegetarian', TRUE, 'lunch', 360, 24, 20, 20, 6, 2.5, 280, 70, 'dairy', 'grilled', 'all_year');
INSERT INTO foods (name, region, state, diet_type, is_jain_friendly, meal_slot, calories_per_serving, protein_g, carbs_g, fat_g, fiber_g, iron_mg, calcium_mg, price_inr_per_serving, allergens, prep_method, seasonality) VALUES ('Sprout & Vegetable Salad', 'pan_india', '', 'vegan', TRUE, 'lunch', 240, 12, 32, 5, 9, 3.2, 40, 30, '', 'raw', 'all_year');
INSERT INTO foods (name, region, state, diet_type, is_jain_friendly, meal_slot, calories_per_serving, protein_g, carbs_g, fat_g, fiber_g, iron_mg, calcium_mg, price_inr_per_serving, allergens, prep_method, seasonality) VALUES ('Mixed Vegetable Pulao', 'pan_india', '', 'vegetarian', TRUE, 'lunch', 380, 8, 58, 10, 4, 2.0, 30, 30, '', 'boiled', 'all_year');
INSERT INTO foods (name, region, state, diet_type, is_jain_friendly, meal_slot, calories_per_serving, protein_g, carbs_g, fat_g, fiber_g, iron_mg, calcium_mg, price_inr_per_serving, allergens, prep_method, seasonality) VALUES ('Tofu Stir Fry + Rice', 'pan_india', '', 'vegan', TRUE, 'lunch', 400, 20, 48, 14, 5, 3.5, 200, 40, 'soy', 'sauteed', 'all_year');
INSERT INTO foods (name, region, state, diet_type, is_jain_friendly, meal_slot, calories_per_serving, protein_g, carbs_g, fat_g, fiber_g, iron_mg, calcium_mg, price_inr_per_serving, allergens, prep_method, seasonality) VALUES ('Chicken Biryani (1 plate)', 'pan_india', '', 'non_vegetarian', FALSE, 'lunch', 550, 28, 60, 20, 3, 2.5, 40, 80, '', 'sauteed', 'all_year');
INSERT INTO foods (name, region, state, diet_type, is_jain_friendly, meal_slot, calories_per_serving, protein_g, carbs_g, fat_g, fiber_g, iron_mg, calcium_mg, price_inr_per_serving, allergens, prep_method, seasonality) VALUES ('Veg Biryani (1 plate)', 'pan_india', '', 'vegetarian', TRUE, 'lunch', 440, 10, 64, 14, 5, 2.5, 40, 45, '', 'sauteed', 'all_year');
INSERT INTO foods (name, region, state, diet_type, is_jain_friendly, meal_slot, calories_per_serving, protein_g, carbs_g, fat_g, fiber_g, iron_mg, calcium_mg, price_inr_per_serving, allergens, prep_method, seasonality) VALUES ('Khichdi + Kadhi', 'pan_india', '', 'vegetarian', TRUE, 'lunch', 400, 14, 56, 10, 6, 3.0, 120, 30, 'dairy', 'boiled', 'all_year');
INSERT INTO foods (name, region, state, diet_type, is_jain_friendly, meal_slot, calories_per_serving, protein_g, carbs_g, fat_g, fiber_g, iron_mg, calcium_mg, price_inr_per_serving, allergens, prep_method, seasonality) VALUES ('Chapati + Mixed Veg + Dal', 'pan_india', '', 'vegan', TRUE, 'lunch', 420, 14, 58, 10, 8, 3.5, 60, 35, 'gluten', 'sauteed', 'all_year');
INSERT INTO foods (name, region, state, diet_type, is_jain_friendly, meal_slot, calories_per_serving, protein_g, carbs_g, fat_g, fiber_g, iron_mg, calcium_mg, price_inr_per_serving, allergens, prep_method, seasonality) VALUES ('Mixed Millet Khichdi', 'pan_india', '', 'vegan', TRUE, 'dinner', 380, 12, 65, 8, 9, 3.4, 50, 30, '', 'boiled', 'all_year');
INSERT INTO foods (name, region, state, diet_type, is_jain_friendly, meal_slot, calories_per_serving, protein_g, carbs_g, fat_g, fiber_g, iron_mg, calcium_mg, price_inr_per_serving, allergens, prep_method, seasonality) VALUES ('Grilled Chicken Breast + Salad', 'pan_india', '', 'non_vegetarian', FALSE, 'dinner', 400, 40, 12, 16, 5, 1.8, 30, 110, '', 'grilled', 'all_year');
INSERT INTO foods (name, region, state, diet_type, is_jain_friendly, meal_slot, calories_per_serving, protein_g, carbs_g, fat_g, fiber_g, iron_mg, calcium_mg, price_inr_per_serving, allergens, prep_method, seasonality) VALUES ('Mushroom + Capsicum + Roti', 'pan_india', '', 'vegan', TRUE, 'dinner', 340, 10, 46, 10, 6, 3.0, 20, 30, 'gluten', 'sauteed', 'all_year');
INSERT INTO foods (name, region, state, diet_type, is_jain_friendly, meal_slot, calories_per_serving, protein_g, carbs_g, fat_g, fiber_g, iron_mg, calcium_mg, price_inr_per_serving, allergens, prep_method, seasonality) VALUES ('Paneer Tikka (8 pcs)', 'pan_india', '', 'vegetarian', TRUE, 'dinner', 380, 22, 16, 24, 3, 2.0, 300, 60, 'dairy', 'grilled', 'all_year');
INSERT INTO foods (name, region, state, diet_type, is_jain_friendly, meal_slot, calories_per_serving, protein_g, carbs_g, fat_g, fiber_g, iron_mg, calcium_mg, price_inr_per_serving, allergens, prep_method, seasonality) VALUES ('Egg Bhurji + 2 Chapati', 'pan_india', '', 'eggetarian', FALSE, 'dinner', 440, 20, 38, 22, 3, 3.0, 60, 40, 'eggs,gluten', 'sauteed', 'all_year');
INSERT INTO foods (name, region, state, diet_type, is_jain_friendly, meal_slot, calories_per_serving, protein_g, carbs_g, fat_g, fiber_g, iron_mg, calcium_mg, price_inr_per_serving, allergens, prep_method, seasonality) VALUES ('Dal Tadka + Rice', 'pan_india', '', 'vegan', TRUE, 'dinner', 420, 14, 60, 10, 6, 3.5, 40, 30, '', 'boiled', 'all_year');
INSERT INTO foods (name, region, state, diet_type, is_jain_friendly, meal_slot, calories_per_serving, protein_g, carbs_g, fat_g, fiber_g, iron_mg, calcium_mg, price_inr_per_serving, allergens, prep_method, seasonality) VALUES ('Curd Rice (Light)', 'pan_india', '', 'vegetarian', TRUE, 'dinner', 280, 8, 42, 6, 1, 0.8, 160, 20, 'dairy', 'raw', 'summer');
INSERT INTO foods (name, region, state, diet_type, is_jain_friendly, meal_slot, calories_per_serving, protein_g, carbs_g, fat_g, fiber_g, iron_mg, calcium_mg, price_inr_per_serving, allergens, prep_method, seasonality) VALUES ('Vegetable Soup + Bread', 'pan_india', '', 'vegan', TRUE, 'dinner', 200, 6, 30, 4, 5, 1.5, 30, 15, 'gluten', 'boiled', 'all_year');
INSERT INTO foods (name, region, state, diet_type, is_jain_friendly, meal_slot, calories_per_serving, protein_g, carbs_g, fat_g, fiber_g, iron_mg, calcium_mg, price_inr_per_serving, allergens, prep_method, seasonality) VALUES ('Buttermilk (Chaas, 300ml)', 'pan_india', '', 'vegetarian', TRUE, 'snack', 80, 3, 6, 4, 0, 0.2, 120, 10, 'dairy', 'blended', 'summer');
INSERT INTO foods (name, region, state, diet_type, is_jain_friendly, meal_slot, calories_per_serving, protein_g, carbs_g, fat_g, fiber_g, iron_mg, calcium_mg, price_inr_per_serving, allergens, prep_method, seasonality) VALUES ('Fruit Bowl (Mixed, 200g)', 'pan_india', '', 'vegan', TRUE, 'snack', 120, 2, 28, 1, 4, 0.5, 30, 10, '', 'raw', 'all_year');
INSERT INTO foods (name, region, state, diet_type, is_jain_friendly, meal_slot, calories_per_serving, protein_g, carbs_g, fat_g, fiber_g, iron_mg, calcium_mg, price_inr_per_serving, allergens, prep_method, seasonality) VALUES ('Peanut Chikki (50g)', 'pan_india', '', 'vegan', TRUE, 'snack', 210, 7, 22, 11, 3, 1.5, 20, 20, 'nuts', 'raw', 'winter');
INSERT INTO foods (name, region, state, diet_type, is_jain_friendly, meal_slot, calories_per_serving, protein_g, carbs_g, fat_g, fiber_g, iron_mg, calcium_mg, price_inr_per_serving, allergens, prep_method, seasonality) VALUES ('Boiled Egg (2) + Fruit', 'pan_india', '', 'eggetarian', FALSE, 'snack', 220, 14, 20, 10, 3, 1.8, 50, 30, 'eggs', 'boiled', 'all_year');
INSERT INTO foods (name, region, state, diet_type, is_jain_friendly, meal_slot, calories_per_serving, protein_g, carbs_g, fat_g, fiber_g, iron_mg, calcium_mg, price_inr_per_serving, allergens, prep_method, seasonality) VALUES ('Dry Fruits Mix (30g)', 'pan_india', '', 'vegan', TRUE, 'snack', 180, 5, 14, 12, 2, 1.2, 40, 25, 'nuts', 'raw', 'all_year');
INSERT INTO foods (name, region, state, diet_type, is_jain_friendly, meal_slot, calories_per_serving, protein_g, carbs_g, fat_g, fiber_g, iron_mg, calcium_mg, price_inr_per_serving, allergens, prep_method, seasonality) VALUES ('Masala Chana (100g)', 'pan_india', '', 'vegan', TRUE, 'snack', 160, 8, 24, 3, 6, 2.8, 50, 10, '', 'boiled', 'all_year');
INSERT INTO foods (name, region, state, diet_type, is_jain_friendly, meal_slot, calories_per_serving, protein_g, carbs_g, fat_g, fiber_g, iron_mg, calcium_mg, price_inr_per_serving, allergens, prep_method, seasonality) VALUES ('Yogurt Parfait', 'pan_india', '', 'vegetarian', TRUE, 'snack', 200, 8, 28, 6, 2, 0.5, 150, 25, 'dairy,nuts', 'raw', 'all_year');
INSERT INTO foods (name, region, state, diet_type, is_jain_friendly, meal_slot, calories_per_serving, protein_g, carbs_g, fat_g, fiber_g, iron_mg, calcium_mg, price_inr_per_serving, allergens, prep_method, seasonality) VALUES ('Protein Shake (Whey+Banana)', 'pan_india', '', 'vegetarian', TRUE, 'snack', 250, 25, 28, 4, 2, 1.0, 200, 30, 'dairy', 'blended', 'all_year');
INSERT INTO foods (name, region, state, diet_type, is_jain_friendly, meal_slot, calories_per_serving, protein_g, carbs_g, fat_g, fiber_g, iron_mg, calcium_mg, price_inr_per_serving, allergens, prep_method, seasonality) VALUES ('Green Tea + Almonds (10)', 'pan_india', '', 'vegan', TRUE, 'snack', 100, 4, 6, 7, 2, 0.8, 50, 5, 'nuts', 'brewed', 'all_year');
INSERT INTO foods (name, region, state, diet_type, is_jain_friendly, meal_slot, calories_per_serving, protein_g, carbs_g, fat_g, fiber_g, iron_mg, calcium_mg, price_inr_per_serving, allergens, prep_method, seasonality) VALUES ('Makhana Roasted (50g)', 'pan_india', '', 'vegan', TRUE, 'snack', 180, 5, 28, 4, 3, 1.8, 40, 12, '', 'roasted', 'all_year');
INSERT INTO foods (name, region, state, diet_type, is_jain_friendly, meal_slot, calories_per_serving, protein_g, carbs_g, fat_g, fiber_g, iron_mg, calcium_mg, price_inr_per_serving, allergens, prep_method, seasonality) VALUES ('Ragi Ladoo (2 pcs)', 'pan_india', '', 'vegetarian', TRUE, 'snack', 200, 4, 30, 8, 3, 2.0, 80, 15, 'dairy', 'raw', 'all_year');